### PR TITLE
updated gradle to use 2.1 and plugin 1.0, updated min sdk version to 14

### PR DESCRIPTION
**Pull request by nicholasjackson**
Hi,

The android manifest in the library has on explicit SDK version set, this causes the below permission to be implied and thus filters down into our app which uses the library.

* READ_PHONE_STATE

If the SDK version is > 3 then this permission is no longer implied, I have updated the android manifest to explicitly set an SDK version of 14 as specified in your docs and also updated the gradle plugin build tools and compile sdk to the latest versions.

Kind regards,

Nic

### CODE REVIEW

**Comment by sarfata** [comment]
Thanks @nicholasjackson. We will look at this!

**Comment by matthewtole** [comment]
Hi @nicholasjackson. We have merged this fix internally and it will be released in the next version.

**Comment by nicholasjackson** [comment]
Superb thanks,

Nic

**Comment by jay3** [comment]
Thanks a lot!

**Pull request closed without merging**
